### ISSUE TITLE
How to model multiple lower level programs?

### ISSUE THREAD

**Issue by skampezidou** [joaquimg/BilevelJuMP.jl#201] opened 2023-05-28 16:23 UTC
Can we have an example script that works? Thank you.

**Comment by odow** [comment] 2023-06-09 23:01
Duplicate of https://github.com/joaquimg/BilevelJuMP.jl/issues/1

**Comment by joaquimg** [comment] 2023-09-14 02:23
I will close as conversation will be tracked in #1

**Closed by joaquimg** 2023-09-14 02:23 UTC
