### ISSUE TITLE
"UndefVarError: _has_nlp_data not defined" when running the example case

### ISSUE THREAD

**Issue by Bittencourt** [joaquimg/BilevelJuMP.jl#204] opened 2023-07-03 14:19 UTC
Hi, I'm trying to run the example case from the docs but getting the following error:

```Python Console
ERROR: UndefVarError: _has_nlp_data not defined
Stacktrace:
 [1] optimize!(model::BilevelModel; lower_prob::String, upper_prob::String, bilevel_prob::String, solver_prob::String, file_format::MathOptInterface.FileFormats.FileFormat, _differentiation_backend::MathOptInterface.Nonlinear.SparseReverseMode)
   @ BilevelJuMP C:\Users\pedro\.julia\packages\BilevelJuMP\Pkp1I\src\jump.jl:641
 [2] optimize!(model::BilevelModel)
   @ BilevelJuMP C:\Users\pedro\.julia\packages\BilevelJuMP\Pkp1I\src\jump.jl:617
```
I`m not sure if it is a compatibility issue due to the version I`m using, but the code is as:

```Julia
using BilevelJuMP, HiGHS, JuMP

model = BilevelModel(
    HiGHS.Optimizer,
    mode = BilevelJuMP.FortunyAmatMcCarlMode(primal_big_M = 100, dual_big_M = 100)
)

@variable(Lower(model), x)
@variable(Upper(model), y)

@objective(Upper(model), Min, 3x + y)
@constraints(Upper(model), begin
    x <= 5
    y <= 8
    y >= 0
end)

@objective(Lower(model), Min, -x)
@constraints(Lower(model), begin
     x +  y <= 8
    4x +  y >= 8
    2x +  y <= 13
    2x - 7y <= 0
end)

optimize!(model)
```

Julia version is

```Python Console
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 4 × Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, broadwell)
  Threads: 1 on 4 virtual cores
```

Thank you!

**Comment by joaquimg** [comment] 2023-07-03 23:28
Indeed I cant reproduce.

can you run:
```julia
import Pkg
Pkg.status()
```

I am on:

```
  [485130c0] BilevelJuMP v0.6.1
  [87dc4568] HiGHS v1.5.2
```

You might be able to work with a new environment:
```
Pkg.activate("myenv")
Pkg.add("BilevelJuMP")
Pkg.add("HiGHS")
```

**Comment by Bittencourt** [comment] 2023-07-05 19:09
Thanks! it was related to the HiGHS version.

**Comment by odow** [comment] 2023-08-21 21:02
Closing because this seems resolved.

**Closed by odow** 2023-08-21 21:02 UTC
