### ISSUE TITLE
JuMP 1.5

### ISSUE THREAD

**Issue by FabrizioLacalandra** [joaquimg/BilevelJuMP.jl#193] opened 2022-12-16 19:02 UTC
I don't know if this is an issue or a pull request, however the installation of BJump seems to require a step back to JumP 1.1.1 (now 1.5). Is there any workaround or it is strictly needed?

Fabrizio

**Comment by joaquimg** [comment] 2022-12-16 20:05
It it strictly needed because the Non-Linear programming internals in JuMP were updated and are incompatible as of now. It should not be hard fix though

**Comment by odow** [comment] 2022-12-16 21:17
Duplicate of https://github.com/joaquimg/BilevelJuMP.jl/issues/178

**Closed** 2023-02-27 03:01 UTC
