### ISSUE TITLE
Please I'm need solve the bilevel programming model in k.k.t condition..I'm need code and solve 

### ISSUE THREAD

**Issue by OthmanProgramming** [joaquimg/BilevelJuMP.jl#207] opened 2023-08-21 20:06 UTC
Min F(S_1,S_2,S_3 ):850S_1+825S_2+125S_3            
           Min ʄ (S_1,S_2,S_3 ):825S_1+800S_2+100S_3
st:                                                                                                       
500000S_1+436500S_2+386400S_3         ≤2322900           
13.186 S_1+12.321S_2+9.972S_3                    ≤400000           
12S_1+8S_2+5S_3                                                ≤2000                 
100000S_1+100000S_2+800000S_3          ≤1000800       
900S_1+850S_2+125S_3                                    ≤7650000        
S1,S2,S3≥0

**Comment by odow** [comment] 2023-08-21 21:02
Closing as duplicate of https://github.com/joaquimg/BilevelJuMP.jl/issues/206

**Closed by odow** 2023-08-21 21:02 UTC
